- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/ScriptsDoNotContainImportOfChocolateyModuleRequirement.cs
> (GH-27) Don't use Chocolatey Module Requirement

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/InstallScriptsShouldntUseSourceforgeGuideline.cs
> (GH-19) Don't use Sourceforge Guideline

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/TooManyInstallationScriptsGuideline.cs
> (GH-15) Too many installation scripts guideline

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/IncludesChocolateyDependencyNote.cs
> (GH-33) Add Note about Chocolatey Dependency

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/DependencyWithNoVersionGuideline.cs
> (GH-40) Dependency with no version Guideline

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/InstallScriptsUseWscriptNote.cs
> (GH-36) Installation Scripts use WScript Note

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/DependencyWithNoVersionGuidelineSpecs.cs
- src/chocolatey.package.validator/infrastructure.app/rules/DependencyWithNoVersionGuideline.cs
> (GH-57) Adding specs for checking dependency version

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/InstallScriptsShouldntUseCreateShortcutNote.cs
> (GH-35) Don't use .CreateShortcut Note

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/InstallScriptsShouldntUseInstallArgumentsRequirement.cs
> (GH-29) Don't use Installation Arguments Requirement

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/AdminTagShouldBeIncludedWhenUsingAdminHelpersGuidelineSpecs.cs
- src/chocolatey.package.validator/StringExtensions.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/AdminTagShouldBeIncludedWhenUsingAdminHelpersGuideline.cs
> (GH-38) Include Admin Tag when using Admin Helpers

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/ChocoInstallShouldntCallChocoUninstallRequirement.cs
> (GH-61) Install shouldn't call Uninstall Requirement

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/NotSilentTagIsBeingUsedNote.cs
> (GH-66) notSilent Tag Is Used Note

- src/chocolatey.package.validator/StreamExtensions.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/NuspecFileShouldBeUtf8Guideline.cs
> (GH-71) Nuspec should be UTF-8 Guideline

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/CopyrightAndAuthorFieldsShouldntContainEmailRequirementSpecs.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/CopyRightAndAuthorFieldsShouldntContainEmailRequirement.cs
> (GH-96) No emails in Fields Requirement

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/PackageIdTooLongWithNoDashesNoteSpecs.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/PackageIdTooLongWithNoDashesNote.cs
> (GH-80) Package Id too long and no dashes Note

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/TagsDoNotContainChocolateyRequirementSpecs.cs
- src/chocolatey.package.validator/infrastructure.app/rules/TagsDoNotContainChocolateyRequirement.cs
> (GH-101) Correcting issue with detecting chocolatey tag

- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/OperatingSystemIndexFilesAreNotPackagedRequirement.cs
- src/chocolatey.package.validator/infrastructure.app/rules/SourceControlInternalFilesAreNotPackagedRequirement.cs
> (GH-94) Add check for .DS_Store file

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/PrereleaseVersionAsPartOfPackageIdRequirementSpecs.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/PrereleaseVersionAsPartOfPackageIdRequirement.cs
> (GH-92) No Version Info in ID Requirement

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/SourceControlIgnoreFilesAreNotPackagedRequirementSpecs.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/SourceControlIgnoreFilesAreNotPackagedRequirement.cs
> (GH-119) No Source Control Ignore Files Requirement

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/PackageIdUsesUnderscoresNoteSpecs.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/PackageIdUsesUnderscoresNote.cs
> (GH-90) Added Note for using underscore

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/DescriptionWordCountMinimum30GuidelineSpecs.cs
> (GH-136) Added test for minimum description

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/DescriptionWordCountMaximum4000RequirementSpecs.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/DescriptionWordCountMaximum4000Requirement.cs
> (GH-134) Added rule for maximum description

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/AdminHelpersShouldBeIncludedWhenUsingAdminTagGuideline.cs
- src/chocolatey.package.validator/chocolatey.package.validator.csproj
- src/chocolatey.package.validator/infrastructure.app/rules/AdminHelpersShouldBeIncludedWhenUsingAdminTagGuideline.cs
> (GH-99) Add rule for usage of admin tag

- src/chocolatey.package.validator.tests/chocolatey.package.validator.tests.csproj
- src/chocolatey.package.validator.tests/infrastructure.app/BinariesAreIncludedNoteSpecs.cs
- src/chocolatey.package.validator/infrastructure.app/rules/BinariesAreIncludedNote.cs
> (GH-124) Extend Binary Rule to include other type of binary file

- src/chocolatey.package.validator/infrastructure.app/rules/CopyRightAndAuthorFieldsShouldntContainEmailRequirement.cs
The wiki url was incorrect.
Related to #187
> (GH-187) fixed copyright url
